### PR TITLE
Full Pass

### PR DESCRIPTION
**Pull request by OR13**
Many changes in here, there was a lot of stale content, unused references, and some missing section headers.

I filed several issues and added them to relevant sections.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/pull/86.html" title="Last updated on May 1, 2023, 3:18 PM UTC (9975fcc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/86/bb7ac47...9975fcc.html" title="Last updated on May 1, 2023, 3:18 PM UTC (9975fcc)">Diff</a>

### CODE REVIEW

**Comment by OR13** [comment]
If this PR is merged, we should be able to close:

- https://github.com/w3c/vc-di-bbs/issues/75
- https://github.com/w3c/vc-di-bbs/issues/61

**Review by dlongley — APPROVED** [review]
This is ok for now -- still needs iteration later (like simplifying `proofValue`, IMO), but that's for debating in issues and future PRs.

**Comment by OR13** [comment]
I am merging this ahead of preparing the FPWD.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-05-03-vcwg#section2-1) on 2023-05-03

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Full Pass (pr vc-di-bbs#86)

_See github pull request [vc-di-bbs#86](https://github.com/w3c/vc-di-bbs/pull/86)._




**Orie Steele:** open PR that has a full pass on. covers substantial amount of updates.  
… is it ok to merge the PR before running through doc checker?  
… i want to direct attention to PR. a lot of stale content in the PR.  
… should be advantageous to merge it.  
… if merge PR then can easily issues that FPWD might surface.  

**Ivan Herman:** if you cannot finish doc by today then tomorrow we cannot run whole thing and this might be problem because next week there won't be a meeting. that might put the publishing date at risk.  
… unfortunate because AC meeting next week.  

**Orie Steele:** PR addresses several issues. fixes linking scenarios. that is the part to ask for permissions to merge.  

> *Dave Longley:* +1 to merge this PR.

**Brent Zundel:** would accelerate ability to create FPWD draft?  

**Orie Steele:** correct.  

**Brent Zundel:** as long as sign off by co-editor, then go for it. since FPWD we are very early on anyways.  

> *PDL ASU:* no objections here.

**Brent Zundel:** any objections to that course of actions?  

**Orie Steele:** i doubt tobias (co-editor) can review this on time.  

**Brent Zundel:** no objections noted.  
… tobias' approval does not have to be super formal as long as it exists.  

**Orie Steele:** if objections then i will revert it.  
… but unlikely there will be any.  

**Brent Zundel:** comfortable with that approach.  

</details>

**Pull request merged**
